; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
# No default environment, we'll specify which to use

[env:bmp_basic]
platform = ststm32
board = genericSTM32F103ZE
framework = arduino
upload_protocol = blackmagic
upload_port = COM3
debug_tool = blackmagic
debug_port = ${this.upload_port}
monitor_port = COM4
monitor_speed = 115200

[env:bmp_srst]
extends = env:bmp_basic
debug_port = ${this.upload_port} connect_srst

[env:bmp_tpwr]
extends = env:bmp_basic
debug_port = ${this.upload_port} tpwr

[env:bmp_both]
extends = env:bmp_basic
debug_port = ${this.upload_port} connect_srst tpwr
framework = arduino
